# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/DDS/DDS.srcs/sources_1/ip/ROM_SQURE/ROM_SQURE.xci
# IP: The module: 'ROM_SQURE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DDS/DDS.srcs/sources_1/ip/ROM_SQURE/ROM_SQURE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_SQURE'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/DDS/DDS.srcs/sources_1/ip/ROM_SQURE/ROM_SQURE.xci
# IP: The module: 'ROM_SQURE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DDS/DDS.srcs/sources_1/ip/ROM_SQURE/ROM_SQURE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_SQURE'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
